services:
  mysql:
    image: mysql:8.3.0
    container_name: mysql-inventory-service
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: example
    ports:
      - "3316:3306"
    volumes:
      - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./docker/mysql_data:/var/lib/mysql

